from typing import Protocol

class CryptographyService(Protocol):
    def hash(self, str_to_hash: str) -> str: ...

    def compare_to_hash(self, unhashed: str, hashed: str) -> bool: ...

    def deterministic_hash(self, value: str) -> str: ...

    def encrypt(self, data: str | int) -> str: ...

    def decrypt(self ,encrypted: str) -> str | int: ...